"""Markdown + DOT report generation for the disposable tracer (S03-T3)."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from tracer.analysis import analyze
from tracer.dag import build_dag, to_dot
from tracer.session import trace

WORKLOADS: dict[str, tuple[str, str]] = {
    "parquet_feature_inference": (
        "cobra_pipelines.parquet_feature_inference",
        "b0",
    ),
    "model_ensemble": ("cobra_pipelines.model_ensemble", "b0"),
    "cv_preprocess_inference_postprocess": (
        "cobra_pipelines.cv_preprocess_inference_postprocess",
        "b0",
    ),
}


def _import_call(module_name: str, func_name: str) -> Any:
    module = __import__(module_name, fromlist=[func_name])
    return getattr(module, func_name)


def _ns_summary(ns: float) -> str:
    if ns >= 1e9:
        return f"{ns / 1e9:.3f} s"
    if ns >= 1e6:
        return f"{ns / 1e6:.3f} ms"
    if ns >= 1e3:
        return f"{ns / 1e3:.3f} us"
    return f"{ns:.0f} ns"


def _render_report(
    workload_name: str,
    dag: dict[str, Any],
    analysis: dict[str, Any],
) -> str:
    lines: list[str] = [
        f"# Tracer report: `{workload_name}`",
        "",
        "Generated by the disposable whole-program tracer (S03-T3).",
        "",
        "## Summary",
        "",
        f"* **Total events:** {len(dag['nodes'])}",
        f"* **Total recorded work:** {_ns_summary(analysis['total_work_ns'])}",
        f"* **Critical path (span):** {_ns_summary(analysis['critical_path_ns'])}",
        f"* **Max theoretical speedup:** {analysis['max_speedup']:.2f}x",
        f"* **Estimated transfer boundaries:** {analysis['transfer_count_estimate']}",
        f"* **Candidate parallel regions:** {len(analysis['parallel_regions'])}",
        "",
        "## Top 5 critical-path operations",
        "",
        "| Rank | Op | Duration | % of span |",
        "|------|----|----------|-----------|",
    ]

    for op in analysis["top5_critical_ops"]:
        lines.append(
            f"| {op['rank']} | `{op['op']}` | "
            f"{_ns_summary(op['duration_ns'])} | {op['pct_of_span']:.1f}% |"
        )
    lines.append("")

    lines.extend(["## Transfer boundaries", ""])
    transfers = analysis["transfer_boundaries"]
    if transfers:
        total_ns = sum(t["duration_ns"] for t in transfers)
        # Aggregate by (op, source, target) to keep the report readable when
        # the tracer records many small per-weight moves (e.g. inside resnet18).
        agg: dict[tuple[str, str, str], dict[str, Any]] = defaultdict(
            lambda: {"count": 0, "duration_ns": 0, "max_id": 0}
        )
        for t in transfers:
            key = (t["op"], t["source"], t["target"])
            entry = agg[key]
            entry["count"] += 1
            entry["duration_ns"] += t["duration_ns"]
            entry["max_id"] = max(entry["max_id"], t["id"])
        grouped = sorted(
            [
                {
                    "op": k[0],
                    "source": k[1],
                    "target": k[2],
                    "count": v["count"],
                    "duration_ns": v["duration_ns"],
                    "max_id": v["max_id"],
                }
                for k, v in agg.items()
            ],
            key=lambda x: x["duration_ns"],
            reverse=True,
        )
        lines.append(
            f"Detected {len(transfers)} explicit host/device transfer(s); "
            f"total estimated transfer time: {_ns_summary(total_ns)}."
        )
        lines.append("Aggregated by op, source, and target below.")
        lines.append("")
        lines.append("| Op | Source | Target | Count | Total | Max node |")
        lines.append("|----|--------|--------|-------|-------|----------|")
        for g in grouped:
            lines.append(
                f"| `{g['op']}` | {g['source']} | {g['target']} | "
                f"{g['count']} | {_ns_summary(g['duration_ns'])} | {g['max_id']} |"
            )
    else:
        lines.append("No explicit host/device transfers detected in this trace.")
    lines.append("")

    lines.extend(["## Device residency timeline", ""])
    transitions: list[dict[str, Any]] = []
    prev: str | None = None
    for row in analysis["device_timeline"]:
        if row["device"] != prev:
            transitions.append(row)
            prev = row["device"]
    lines.append(f"Showing the {len(transitions)} host/device transition point(s).")
    lines.append("")
    lines.append("| Node | Op | Device |")
    lines.append("|------|----|--------|")
    for row in transitions:
        lines.append(f"| {row['id']} | `{row['op']}` | {row['device']} |")
    lines.append("")

    lines.extend(["## Candidate parallel regions", ""])
    regions = analysis["parallel_regions"]
    if regions:
        lines.append(f"Showing the top {min(5, len(regions))} regions by parallelizable work.")
        lines.append("")
        for idx, region in enumerate(regions[:5], start=1):
            lines.append(
                f"### Region {idx}: `{region['fork_op']}` (node {region['fork_id']}) "
                f"→ `{region['join_op']}` (node {region['join_id']})"
            )
            lines.append("")
            lines.append(f"* Branch nodes: {sorted(region['branch_ids'])}")
            lines.append(f"* Region span (sequential): {_ns_summary(region['span_ns'])}")
            lines.append(
                f"* Parallelizable work overlap opportunity: "
                f"{_ns_summary(region['parallelizable_ns'])}"
            )
            lines.append("")
    else:
        lines.append("No fork/join parallel regions detected in this trace.")
        lines.append("")

    lines.extend(["## Rendered DAG (Graphviz DOT)", "", "```dot", to_dot(dag), "```", ""])

    return "\n".join(lines) + "\n"


def write_report(
    workload_name: str,
    out_dir: Path,
    dag: dict[str, Any],
    analysis: dict[str, Any],
) -> None:
    """Write a Markdown report and a separate DOT file for ``workload_name``."""
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"{workload_name}.md"
    dot_path = out_dir / f"{workload_name}.dot"

    md_path.write_text(_render_report(workload_name, dag, analysis), encoding="utf-8")
    dot_path.write_text(to_dot(dag), encoding="utf-8")


def _trace_workload(workload_name: str) -> dict[str, Any]:
    module_name, func_name = WORKLOADS[workload_name]
    func = _import_call(module_name, func_name)
    with trace() as session:
        func()
    return build_dag(session.events)


def _generate_for_workload(workload_name: str, out_dir: Path) -> None:
    dag = _trace_workload(workload_name)
    result = analyze(dag)
    write_report(workload_name, out_dir, dag, result)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate disposable-tracer analysis reports for Cobra workloads."
    )
    parser.add_argument(
        "--workload",
        choices=[*list(WORKLOADS.keys()), "all"],
        default="all",
        help="Workload to trace and report on (default: all).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("experimental/tracer/reports"),
        help="Output directory for Markdown and DOT reports.",
    )
    args = parser.parse_args(argv)

    out_dir: Path = args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    names = list(WORKLOADS.keys()) if args.workload == "all" else [args.workload]

    for name in names:
        print(f"Tracing {name} ...", file=sys.stderr)
        _generate_for_workload(name, out_dir)
        print(f"Wrote {out_dir / name}.md and {out_dir / name}.dot", file=sys.stderr)

    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
